### ISSUE TITLE
Issue Update Card

### ISSUE THREAD

**Issue by Andryel-Blanco** [rwjdk/TrelloDotNet#29]
Hi guys, I'm having a problem when I try to update a card
Code:
![image](https://github.com/rwjdk/TrelloDotNet/assets/111362536/de090c99-570a-4e14-9c8c-957a8dbdf190)

Error:
Model.TrelloApiException: '{"message":"Invalid objectId","error":"ERROR"}'

**Comment by rwjdk** [comment]
Hi, based on your screenshot, my best guess here is that your 

newCard.MemberIds;

contains an id of a member that is not present on the board where the 'existingCard' is on... Try as a test to comment out this line to verify this is correct or not, and if it is then make sure all member-ids are valid for the board
