### ISSUE TITLE
CardCover Color Not added for new card

### ISSUE THREAD

**Issue by accjon** [rwjdk/TrelloDotNet#30]
Using AddCardAsync example, card cover is not added.

newAdvancedCard.Cover = new CardCover(CardCoverColor.Blue, CardCoverSize.Normal);

Card created but the cover is not added.

**Comment by rwjdk** [comment]
Hi @accjon . Thank you for reporting this bug... It is indeed not adding the Cover, but I've just fixed this in the code so NuGet Package 1.10.0 will resolve the issue (available in a few minutes).

**Comment by accjon** [comment]
Thanks @rwjdk! That was quick!!
