### ISSUE TITLE
Retrieving Labels - limited to 50 max

### ISSUE THREAD

**Issue by gwill1010** [rwjdk/TrelloDotNet#43]
I think I'm correct, but by default only 50 cards are returned by GetLabelsOfBoardAsync.  We've got many labels and many are archived.  With the Trello API the limit of 50 can be overridden.  With TrelloDotNet can I raise the limit or filter by Open labels? 
thanks

**Comment by rwjdk** [comment]
I'm not sure I follow you here... It seems like you are mixing up various different concepts here... GetLabelsOfBoardAsync has nothing to do with cards (it gives back what available cards that are possible to put on cards; not cards with labels on them). Labels can't be archived either (Only cards and lists can be archived)

Can you please elaborate what you mean?

**Comment by rwjdk** [comment]
As for the limit I see it is there (https://developer.atlassian.com/cloud/trello/rest/api-group-boards/#api-boards-id-labels-get) by default if that is what you are talking about and I will add an overload that can raise the limit... But it still have nothing to do with cards or archive/unarchive, so still unsure that is what you are rally asking for

**Comment by gwill1010** [comment]
Very sorry, I did mean labels, not cards.

**Comment by rwjdk** [comment]
Ok, nuget package 1.11.1 is out that support it (extra parameter on the method caalled GetLabelOptions where you can set the limit)

**Comment by gwill1010** [comment]
Tested, works perfectly.  Thanks again.
